### ISSUE TITLE
Bug: v0.0.42 crashes on startup

### ISSUE THREAD

**Issue by kwrobert** [WorldBrain/memex-local-sync#10]
Downloaded version 0.0.42 and it crashes on startup with the following traceback:

<img width="540" alt="Screenshot 2024-01-02 at 8 14 59 AM" src="https://github.com/WorldBrain/memex-desktop/assets/8059043/04377cea-b393-4fa7-96cc-d9702da5b5b2">

Here is the traceback text:

```
Uncaught Exception:
Error: vectordb: failed to load native library.
You may need to run `npm install @lancedb/vectordb-darwin-x64`.

If that does not work, please file a bug report at https://github.com/lancedb/lancedb/issues

Source error: Error: Cannot find module '@lancedb/vectordb-darwin-x64'
Require stack:
- /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/native.js
- /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/query.js
- /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/remote/index.js
- /Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/index.js
at Object.<anonymous> (/Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/native.js:26:11)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at Module._load (node:internal/modules/cjs/loader:967:12)
at l._load (node:electron/js2c/asar_bundle:2:13642)
at Module.require (node:internal/modules/cjs/loader:1150:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/Applications/Memex-Desktop.app/Contents/Resources/app/node_modules/vectordb/dist/query.js:28:25)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
```
Running on macOS Ventura 13.2.1, let me know if more information about my environment would be helpful, happy to provide it.

**Comment by kwrobert** [comment]
Upgraded to macOS Sonoma 14.2.1 and I'm still experiencing the same issue.
